language: php

php:
    - 7.1

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    - COMPOSER_FLAGS="--prefer-dist --optimize-autoloader --no-interaction --no-suggest"

matrix:
    include:
        - php: 7.1

before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini || true

install:
    - php -d memory_limit=-1 $(phpenv which composer) update $COMPOSER_FLAGS

script:
    - if [ "$VALIDATE_DOCS" != true ]; then ./vendor/bin/phpunit; fi
